# Generated by Django 3.1.2 on 2020-10-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomfor', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('fono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pasteles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nompas', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('12', '12 Personas'), ('16', '16 Personas'), ('18', '18 Personas'), ('24', '24 Personas'), ('30', '30 Personas'), ('36', '36 Personas'), ('45', '45 Personas')], default='12', help_text='Cantidad de personas', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ape', models.CharField(max_length=50)),
                ('dire', models.CharField(max_length=150)),
                ('contra', models.CharField(max_length=30)),
            ],
        ),
    ]
